### ISSUE TITLE
Adding custom images instead of yours

### ISSUE THREAD

**Issue by mehrdad-shokri** [alexfi/pomodrone-web#1]
Thanks for open sourcing this site,  
I want to know how can I replace your SVGs with my own custom ones.  
Right now I have a .svg file. Is there any easy way to replace with site's images?

**Comment by dilizarov-wrap** [comment]
+1

**Comment by alexfi** [comment]
@mehrdaad sorry, but no easy way, I'm afraid, you'll have to figure it out to make it match your needs.
I'm working on an update of the app itself and this landing will also be updated.
I'll do my best to make it more developer-friendly.

**Comment by mehrdad-shokri** [comment]
@alexfi thanks anyway. good luck!
